name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMMIT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # - name: Cache Maven packages
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      # - name: Unit Tests
      #   run: mvn -q test

      # - name: Integration Tests
      #   run: mvn integration-test
      
      - name: Login ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push to ghcr
      - name: Push to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: docker/carts/Dockerfile.github
          tags: |
            ghcr.io/${{ github.repository }}:latest
